---
title: "FLC expression statistics"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load_dplyr, echo=T, results='hide', message=F, warning=F}
library(dplyr)
```


```{r readtable}
df = read.table('FLCexpression4stats.txt',header = TRUE)
```

## Produce summary statistics

```{r load_FSA, echo=T, results='hide', message=F, warning=F}
library(FSA) 
```

```{r summarize}
Summarize(Ratio ~ Accession,
          data=df,
          digits=3)
```

## Test homoscedasticity

```{r bartlett}
bartlett.test(Ratio ~ Accession,df)
```

## Test normality

```{r qqPlot}
qqnorm(df$Ratio)
qqline(df$Ratio)
```


```{r shapiro}
shapiro.test(df$Ratio)

```

 
## Kruskal-Wallis 

```{r agricolae,echo=T, results='hide', message=F, warning=F}
library(agricolae)
```
 
```{r Kruskal Pvalue}
kru = kruskal(df$Ratio, df$Accession, alpha=0.05, p.adj=c("bonferroni"), group=FALSE)
kru
```

```{r Kruskal Grouped}
kru = kruskal(df$Ratio, df$Accession, alpha=0.05, p.adj=c("bonferroni"), group=TRUE)
kru
```


